id: local              # 客户端ID
server: 127.0.0.1:6154 # 服务器地址
ssl:
  enabled: false       # 是否使用tls连接
  insecure: false      # 是否关闭SNI，若使用自签证书可将其设置为true
dashboard: # web面板
  enabled: true   # 是否开放dashboard
  listen: 0.0.0.0 # 监听地址
  port: 8080      # 监听端口号
#include common.yaml
rules: # rule列表
  #include rule.d/*.yaml